# Generated by Django 5.2.11 on 2026-03-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PESO', 'PESO')], default='USD', max_length=4, verbose_name='Booking currency')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Renter',
                'verbose_name_plural': 'Renters',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
