# Generated by Django 5.2.11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='document',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='renters/%Y/%m/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            'jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp',
                            'pdf', 'doc', 'docx',
                        ]
                    ),
                ],
                verbose_name='Document',
            ),
        ),
    ]
