
# Generated by Django 5.2.11 on 2026-05-05 17:52

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_options_alter_booking_renter'),
        ('fleet', '0006_add_car_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                name='booking_no_overlaps_per_car',
                expressions=[
                    ('car', '='),
                    (
                        models.Func(
                            models.F('start_date'),
                            models.F('end_date'),
                            function='daterange',
                            template="%(function)s(%(expressions)s, '[]')",
                        ),
                        '&&',
                    ),
                ],
                condition=models.Q(('status', 'CANCELLED'), _negated=True),
            ),
        ),
    ]