# Generated by Django 5.2.11 on 2026-03-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='fleet.car', verbose_name='Car'),
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_insurances', to='fleet.insurancecompany', verbose_name='Insurance company'),
        ),
    ]
