# Generated by Django 5.2.11 on 2026-03-04 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(verbose_name='Expense description')),
                ('date', models.DateField(verbose_name='Expense date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expense amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PESO', 'PESO')], default='USD', max_length=4, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Leave empty for base currency (USD) — 1 will be used on save. For other currencies: how much expense currency for 1 unit of base currency (e.g. 60 when 1 USD = 60 PESO).', max_digits=12, null=True, verbose_name='Rate to base currency')),
                ('amount_in_base_currency', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated automatically on save.', max_digits=10, null=True, verbose_name='Amount in base currency')),
                ('base_currency_at_save', models.CharField(default='USD', help_text='Filled automatically on save.', max_length=4, verbose_name='Base currency at save time')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='ExpensePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='expenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx'])], verbose_name='Attachment')),
            ],
            options={
                'verbose_name': 'Expense attachment',
                'verbose_name_plural': 'Expense attachments',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Date received')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PESO', 'PESO')], default='USD', max_length=4, verbose_name='Payment currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Payment curr. per 1 booking curr. (e.g. 60). Save to recalc.', max_digits=12, null=True, verbose_name='Rate')),
                ('amount_in_booking_currency', models.DecimalField(decimal_places=2, help_text='Calculated automatically on save using payment amount and rate.', max_digits=10, verbose_name='Amount in booking currency')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='incomes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx'])], verbose_name='Attachment')),
            ],
            options={
                'verbose_name': 'Payment attachment',
                'verbose_name_plural': 'Payment attachments',
            },
        ),
    ]
