# Generated by Django 5.2.11 on 2026-04-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_options_alter_booking_renter'),
        ('finance', '0005_add_doc_type_to_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='bookings.booking', verbose_name='Car Booking'),
        ),
    ]
