# Generated by Django 6.0.5 on 2026-05-16 22:56

import core.file_processing
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_housebooking'),
        ('finance', '0011_rename_incomephoto_to_incomedocument'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
        migrations.AlterField(
            model_name='expense',
            name='payed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Paid by'),
        ),
        migrations.AlterField(
            model_name='income',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Payment recipient'),
        ),
        migrations.AlterModelTable(
            name='expense',
            table='finance_expense',
        ),
        migrations.AlterModelTable(
            name='income',
            table='finance_income',
        ),
        migrations.CreateModel(
            name='HouseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(verbose_name='Expense description')),
                ('date', models.DateField(verbose_name='Expense date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expense amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PESO', 'PESO')], default='USD', max_length=4, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Leave empty for base currency (USD) — 1 will be used on save. For other currencies: how much expense currency for 1 unit of base currency (e.g. 60 when 1 USD = 60 PESO).', max_digits=12, null=True, verbose_name='Rate to base currency')),
                ('amount_in_base_currency', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated automatically on save.', max_digits=10, null=True, verbose_name='Amount in base currency')),
                ('base_currency_at_save', models.CharField(default='USD', help_text='Filled automatically on save.', max_length=4, verbose_name='Base currency at save time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='properties.house', verbose_name='House')),
                ('payed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Paid by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'House expense',
                'verbose_name_plural': 'House expenses',
                'db_table': 'finance_house_expense',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('file', models.FileField(upload_to='house_expenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx'])], verbose_name='File')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.houseexpense', verbose_name='Expense')),
            ],
            options={
                'verbose_name': 'House expense document',
                'verbose_name_plural': 'House expense documents',
            },
            bases=(core.file_processing.FileProcessingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HouseIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Date received')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PESO', 'PESO')], default='USD', max_length=4, verbose_name='Payment currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Payment curr. per 1 booking curr. (e.g. 60). Save to recalc.', max_digits=12, null=True, verbose_name='Rate')),
                ('amount_in_booking_currency', models.DecimalField(decimal_places=2, help_text='Calculated automatically on save using payment amount and rate.', max_digits=10, verbose_name='Amount in booking currency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('house_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='bookings.housebooking', verbose_name='House booking')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Payment recipient')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'finance_house_income',
            },
        ),
        migrations.CreateModel(
            name='HouseIncomeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('file', models.FileField(upload_to='house_incomes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx'])], verbose_name='File')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.houseincome', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'House payment document',
                'verbose_name_plural': 'House payment documents',
            },
            bases=(core.file_processing.FileProcessingMixin, models.Model),
        ),
    ]
