# Generated by Django 6.0.5 on 2026-05-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_income_options_alter_expense_payed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Car expense', 'verbose_name_plural': 'Car expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensedocument',
            options={'verbose_name': 'Car expense document', 'verbose_name_plural': 'Car expense documents'},
        ),
        migrations.AlterModelOptions(
            name='houseincome',
            options={'verbose_name': 'House income', 'verbose_name_plural': 'House incomes'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Car income', 'verbose_name_plural': 'Car incomes'},
        ),
        migrations.AlterModelOptions(
            name='incomedocument',
            options={'verbose_name': 'Car payment document', 'verbose_name_plural': 'Car payment documents'},
        ),
    ]
